### ISSUE TITLE
Sample data and performance evaluation

### ISSUE THREAD

**Issue by smahajan07** [FENGChenxi0823/SensorCalibration#1]
Can you provide any sample data that you used for the imu-lidar package and what error/accuracy did you get?

Also, my understanding is that the initial guess values for step 2 (handeye example) are slightly perturbed values from step 1 (handeye exporter). Is that correct?

**Comment by FENGChenxi0823** [comment]
Thanks for your attention on this work! 
Right now, I don't have any data stored in my laptop since I 'm not focusing on this part of work recently and not able to get those data in a short time.  You may want to collect your own data and change topic names there accordingly. All the message types are ROS standard, except for the point cloud. As I remember, the ROS bag I used for this package contains x,y,z,intensity and timestamp. The performance evaluation is actually written in Chinese in this folder. I will try to find a time to do a English version if time allows. Thanks for your understanding!

Handeye example takes the exact data exported by exporter, but only utilize the relative transformation there. In the original paper(https://ieeexplore-ieee-org.proxy.lib.umich.edu/document/8593360/citations?tabFilter=papers#citations), they proposed a iterative way to recompute the pose of each sensor to refine the results. However, the handeye dual quaternion solver only run for one iteration in this code which is the shortage compared to the original method.

**Comment by smahajan07** [comment]
1. I do have my own data but wanted to make sure I'm getting sane results from the package.
2. The link you provided doesn't work for me but I'm guessing it's the same paper that you provided in the package description?
3. Could you tell me about the initial guess values that you use in the package? Is it rotation in radians for roll, pitch and yaw and x,y,z translation in meters? From lidar with respect to IMU.

**Comment by FENGChenxi0823** [comment]
Initial guess I used is for the specific car, doesn't make sense to apply
it to your case. You may want to rationalize your results based on the
crispness of point cloud

**Comment by smahajan07** [comment]
Hi,
I understand that your initial guess values are of no use to me. I'm using my own based on my test platform.

**Comment by smahajan07** [comment]
Could you provide some clarification for [this step](https://github.com/FENGChenxi0823/SensorCalibration/blob/master/imu-lidar/examples/HandeyeExample.cpp#L185) 
```
SensorCalibration::HandEye::HandEyeCalibration::estimateHandEyeStandalone(handRotVecs, handTransVecs, eyeRotVecs, eyeTransVecs, calibrationMatrix, summary,true, false);
```

The last argument ```false``` is for use initial guess or not; and inside the ```estimateHandEyeStandalone``` if we use initial guess, it essentially returns the same matrix. Could you clarify this step?

**Comment by smahajan07** [comment]
Also, does the final extrinsic you estimated was around the initial guess? When I run with (or even without) initial guess, I get approx rotation error of a 2-4 degrees and translation error of about 3-15 meters. Which is very high.

**Comment by HRex39** [comment]
> 1. I do have my own data but wanted to make sure I'm getting sane results from the package.
> 2. The link you provided doesn't work for me but I'm guessing it's the same paper that you provided in the package description?
> 3. Could you tell me about the initial guess values that you use in the package? Is it rotation in radians for roll, pitch and yaw and x,y,z translation in meters? From lidar with respect to IMU.

Hello, I have two questions about the Pose information.
1. What kind of coordinate system should I use?(IMU & Lidar)
2. For IMU, if I use UTM coordinate system and radar uses (front x, left y, upper z) coordinate system, how to estimate the initial matrix?
Thank you.
